"""Initial tables

Revision ID: 4b08f8831604
Revises: 1ec117733c54
Create Date: 2025-08-10 19:34:17.686264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b08f8831604'
down_revision = '1ec117733c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('super_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('superheroes')
    op.drop_table('superhero_powers')
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.create_table('superhero_powers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.VARCHAR(), nullable=True),
    sa.Column('hero_id', sa.INTEGER(), nullable=True),
    sa.Column('power_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['superheroes.id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superheroes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('super_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('heroes')
    # ### end Alembic commands ###
